name: Bormeparser CI

on: ["push", "pull_request"]

env:
  PYTHON_VERSION: 3.9.13
  PIP_VERSION: 22.1.2

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: 'Documentation build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip==${{ env.PIP_VERSION }}
          pip install -r requirements_doc.txt
          pip install -e .
          git rev-parse HEAD
      - name: Build html docs
        run: cd docs && make html

  # TODO: add lint job

  test:
    name: 'Bormeparser tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip==${{ env.PIP_VERSION }} wheel
          pip install coveralls
          pip install -r requirements.txt
          ./setup.py -q develop
      - name: Run tests
        run: coverage run --source=bormeparser setup.py test
      - name: Publish to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
